package hook

import (
	"fmt"
	"io"
	"sort"
	"strconv"
	"strings"
)

// tomlValue renders a default as the TOML literal a user would type.
func tomlValue(v any) string {
	switch x := v.(type) {
	case nil:
		return `""`
	case string:
		return strconv.Quote(x)
	case bool:
		return strconv.FormatBool(x)
	case []string:
		parts := make([]string, len(x))
		for i, s := range x {
			parts[i] = strconv.Quote(s)
		}
		return "[" + strings.Join(parts, ", ") + "]"
	default:
		return fmt.Sprintf("%v", x)
	}
}

// WriteConfigExample prints a commented config covering every registered rule.
// Uncommenting a block is exactly how a rule is enabled, so the file states the
// ships-disabled rule by its shape rather than describing it.
func WriteConfigExample(w io.Writer) {
	p := func(format string, args ...any) { _, _ = fmt.Fprintf(w, format+"\n", args...) }

	p("# ollie-hooks — generated by `ollie-hooks config example`. Do not hand-edit.")
	p("#")
	p("# Everything below is commented out, because every rule ships disabled.")
	p("# Uncommenting a [rules.<id>] block is how you turn one on.")
	p("#")
	p("# Defaults shown are the values the rule actually runs with.")

	for _, r := range Registered() {
		p("")
		p("# %s", strings.Repeat("─", 72))
		p("# %s — %s", r.ID, r.Description)
		// Wrapped here but never in the markdown: a config file is read in a
		// terminal, where a 200-column comment is unreadable, while markdown
		// renderers rejoin lines and a wrapped source only costs diff noise.
		for _, line := range docLines(r) {
			for _, wrapped := range wrapText(line, 76) {
				p("# %s", wrapped)
			}
		}
		p("#")
		p("# [rules.%s]", r.ID)
		for _, k := range append(r.UniversalKeys(), r.ConfigKeys()...) {
			writeExampleKey(p, r.ID, k)
		}
	}

	p("")
	p("# %s", strings.Repeat("─", 72))
	p("# Output formatting, shared by every rule.")
	p("#")
	p("# [output]")
	p("# wrap_width = %d   # findings-table width; a hook cannot detect the terminal", defaultWrapWidth)

	p("")
	p("# %s", strings.Repeat("─", 72))
	p("# Rules in another process, speaking JSON on stdin and stdout.")
	p("# verb is a capability: it picks which reply field is read, so a plugin")
	p("# enabled to advise cannot start denying your tool calls after an update.")
	p("#")
	p("# [custom_rules.my-policy]")
	p("# enabled     = true")
	p(`# startup_cmd = "/absolute/path/to/policy.py"   # spawned per event`)
	p(`# server_url  = "http://127.0.0.1:9000/hook"    # or an already-running one`)
	p(`# verb        = "Check"                         # Check|Advise|Gate|Rewrite|Display`)
	p(`# events      = ["PreToolUse"]`)
	p(`# tools       = ["Bash"]`)
	p("# timeout     = %d", defaultRuleTimeout)
}

func writeExampleKey(p func(string, ...any), ruleID string, k KeyDoc) {
	if len(k.Table) > 0 {
		p("#")
		p("# [[rules.%s.%s]]   # %s", ruleID, k.Key, k.Doc)
		for _, sub := range k.Table {
			p("# %-18s = %-20s # %s", sub.Key, tomlValue(sub.Default), sub.Doc)
		}
		return
	}
	p("# %-18s = %-20s # %s", k.Key, tomlValue(k.Default), k.Doc)
}

// WriteRuleSummary prints just the catalogue of shipped rules: what exists and
// what each one does, with no configuration. It is the answer to "what do I get
// if I install this", which is a different question from "how do I tune it".
func WriteRuleSummary(w io.Writer) {
	p := func(format string, args ...any) { _, _ = fmt.Fprintf(w, format+"\n", args...) }

	p("| Rule | Event | Verb | Does |")
	p("| --- | --- | --- | --- |")
	for _, r := range Registered() {
		p("| `%s` | %s | %s | %s |",
			r.ID,
			codeList(eventNames(r.Events)),
			r.verb(),
			cell(r.Description))
	}
}

// ReplaceSection rewrites the body between a pair of HTML comment markers, so a
// generated block can live inside a hand-written document. The markers survive.
func ReplaceSection(doc, name, body string) (string, error) {
	open, close := "<!-- "+name+" -->", "<!-- /"+name+" -->"

	start := strings.Index(doc, open)
	end := strings.Index(doc, close)
	if start < 0 || end < 0 {
		return "", fmt.Errorf("markers %s and %s not found", open, close)
	}
	if end < start {
		return "", fmt.Errorf("marker %s appears before %s", close, open)
	}
	return doc[:start+len(open)] + "\n" + strings.TrimRight(body, "\n") + "\n" + doc[end:], nil
}

// isAssignment reports a bare `key = value` line. Checking for " = " anywhere
// is not enough: doc prose quotes config too, and `match = "opentofu"` inside a
// sentence would otherwise be read back as a live setting.
func isAssignment(line string) bool {
	key, _, found := strings.Cut(line, "=")
	key = strings.TrimSpace(key)
	if !found || key == "" {
		return false
	}
	for _, r := range key {
		lower := r >= 'a' && r <= 'z'
		digit := r >= '0' && r <= '9'
		if !lower && !digit && r != '_' {
			return false
		}
	}
	return true
}

// UncommentExample turns a generated example back into live TOML, keeping only
// the lines that are actually config. It is what a user does by hand when
// enabling a rule, which is what makes it worth testing against.
func UncommentExample(example string) string {
	var out []string
	for _, line := range strings.Split(example, "\n") {
		body, ok := strings.CutPrefix(strings.TrimSpace(line), "# ")
		if !ok {
			continue
		}
		if !strings.HasPrefix(body, "[") && !isAssignment(body) {
			continue
		}
		// Trailing "   # explanation" is prose, not part of the value.
		if i := strings.Index(body, "   #"); i >= 0 {
			body = strings.TrimSpace(body[:i])
		}
		out = append(out, body)
	}
	return strings.Join(out, "\n")
}

// WriteRuleDocs prints the markdown reference: one section per rule.
func WriteRuleDocs(w io.Writer) {
	p := func(format string, args ...any) { _, _ = fmt.Fprintf(w, format+"\n", args...) }

	p("# Rules")
	p("")
	p("Generated by `ollie-hooks docs`. Do not hand-edit.")
	p("")
	p("Every rule ships disabled. Enable one in `~/.config/ollie-hooks/config.toml`:")
	p("")
	p("```toml")
	p("[rules.<id>]")
	p("enabled = true")
	p("```")

	for _, r := range Registered() {
		p("")
		p("## %s", r.ID)
		p("")
		p("%s.", cell(r.Description))
		if lines := docLines(r); len(lines) > 0 {
			p("")
			for _, line := range lines {
				p("%s", line)
			}
		}
		p("")
		p("| | |")
		p("| --- | --- |")
		p("| Events | %s |", codeList(eventNames(r.Events)))
		if len(r.Tools) > 0 {
			p("| Tools | %s |", codeList(r.Tools))
		}
		p("| Verb | %s |", r.verb())
		if len(r.RequiresBinaries) > 0 {
			p("| Needs | %s |", binaryList(r.RequiresBinaries))
		}
		p("| Enabled by default | %s |", yesNo(r.EnabledByDefault))

		p("")
		p("| Key | Default | What it does |")
		p("| --- | --- | --- |")
		for _, k := range append(r.UniversalKeys(), r.ConfigKeys()...) {
			writeDocKey(p, k, "")
		}
	}
}

func writeDocKey(p func(string, ...any), k KeyDoc, prefix string) {
	if len(k.Table) > 0 {
		p("| `%s%s` | table | %s |", prefix, k.Key, k.Doc)
		for _, sub := range k.Table {
			writeDocKey(p, sub, prefix+k.Key+".")
		}
		return
	}
	p("| `%s%s` | `%s` | %s |", prefix, k.Key, tomlValue(k.Default), k.Doc)
}

// WriteRuleList prints the catalogue: what exists, and what each rule is doing
// under the config actually in force — the question "is my rule even on?"
// otherwise has no answer short of reading the debug trace.
func WriteRuleList(w io.Writer) {
	rules := Registered()
	sort.Slice(rules, func(i, j int) bool { return rules[i].ID < rules[j].ID })

	width := 0
	for _, r := range rules {
		if len(r.ID) > width {
			width = len(r.ID)
		}
	}

	_, _ = fmt.Fprintf(w, "%-*s  %-9s %-8s %s\n", width, "RULE", "STATE", "VERB", "DESCRIPTION")
	for _, r := range rules {
		state := "off"
		if RuleEnabled(r.ID, r.EnabledByDefault) {
			state = string(r.severity())
			if r.Check == nil {
				state = "on"
			}
		}
		_, _ = fmt.Fprintf(w, "%-*s  %-9s %-8s %s\n", width, r.ID, state, r.verb(), r.Description)
		if missing := MissingBinaries(r.RequiresBinaries); len(missing) > 0 {
			for _, m := range missing {
				_, _ = fmt.Fprintf(w, "%-*s  %-9s missing %s (%s)\n", width, "", "", m.Bin, m.Install)
			}
		}
	}
}

func docLines(r Rule) []string {
	if strings.TrimSpace(r.Doc) == "" {
		return nil
	}
	return strings.Split(strings.TrimSpace(r.Doc), "\n")
}

func eventNames(events []EventName) []string {
	out := make([]string, len(events))
	for i, e := range events {
		out[i] = string(e)
	}
	return out
}

func codeList(items []string) string {
	out := make([]string, len(items))
	for i, s := range items {
		out[i] = "`" + s + "`"
	}
	return strings.Join(out, ", ")
}

func binaryList(bins []Binary) string {
	out := make([]string, len(bins))
	for i, b := range bins {
		out[i] = "`" + b.Bin + "` (" + b.Install + ")"
	}
	return strings.Join(out, ", ")
}

// cell makes text safe for a markdown table: an unescaped pipe ends the column,
// and a code fence in a description would end the table entirely.
func cell(s string) string {
	s = strings.ReplaceAll(strings.TrimSuffix(s, "."), "|", `\|`)
	return strings.ReplaceAll(s, "```", "`")
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}
